name: Testar com Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testar-python:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Correr os testes
      run: pytest
